import express from 'express';
import userRoutes from './v1/user/user.route';
import testRoutes from './v1/test/test.route';
import authRoutes from './v1/auth/auth.route';
import blogRoutes from './v1/blog/blog.route';
import storyRoutes from './v1/story/story.route';
import planRoutes from './v1/plan/plan.route';
import subscriptionRoutes from './v1/subscription/subscription.route';
import xlsxRoutes from './v1/uploadxlsx/uploadxlsx.route';
import roleRoutes from './v1/Role/role.route';
import dashboardRoutes from './v1/dashboard/dashboard.route';
import KycRoute from './v1/kyc/kyc.route';
import spamRoute from './v1/spamUser/spam.route';
import cancelRequestRoute from './v1/cancelPlan/cancelPlan.route';

const router = express.Router();
router.use('/user', userRoutes);
router.use('/test', testRoutes);
router.use('/auth', authRoutes);
router.use('/blog', blogRoutes);
router.use('/story', storyRoutes);
router.use('/plan', planRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/upload', xlsxRoutes);
router.use('/role', roleRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/kyc', KycRoute);
router.use('/spam', spamRoute);
router.use('/cancel-plan-request', cancelRequestRoute);

module.exports = router;
