import express from 'express';
import userRoutes from './v1/user/user.route';
import testRoutes from './v1/test/test.route';
import authRoutes from './v1/auth/auth.route';
import addressRoutes from './v1/address/addresh.route';
import userProfessionalDetailRoutes from './v1/userProfationalDetail/userProfationalDetail.route';
import friendRoutes from './v1/friend/friend.route';
import storyRoute from './v1/story/story.route';
import blogRoute from './v1/blog/blog.route';
import ShortlistRoute from './v1/shortlist/shortlist.route';
import profileviwerRoute from './v1/profilrviewer/profileviwer.route';
import MessageRoute from './v1/message/message.route';
import privacyRoute from './v1/privacy/privacy.route';
import EmailNotificationRoute from './v1/emailnotification/emailnotification.route';
import NotificationRoute from './v1/notification/notification.route';
import PlanRoute from './v1/plan/plan.route';
import serachRoute from './v1/search/search.route';
import likeRoute from './v1/Like/like.route';
import EducationRoute from './v1/userEducation/userEducatiom.route';
import PratnerRoute from './v1/paertner/partner.route';
import StatusRoute from './v1/status/status.route';
import EmojiRoute from './v1/Emoji/emoji.route';
import OfferRoute from './v1/Offer/offer.route';
import MessageConsentRoute from './v1/MessageConsent/messageconsent.route';
import razorpayRoute from './v1/razorpay/ordercomplete.route';
import searchHistoryRoute from './v1/searchHistory/searchHistory.route';
import spamUserRoute from './v1/spamUser/spamuser.route';
import storyViewRoute from './v1/storyview/storyview.route';
import KycRoute from './v1/kyc/kyc.route';
import datingPartnerRoute from './v1/datingpartner/datinfpartner.route';
import countryCodeRoute from './v1/countryCode/countryCode.route';
import SuccessStoryViewRoute from './v1/SuccessStoryview/SuccessStoryview.route';
import StoryLikeRoute from './v1/storylike/storylike.route';
import userPlanRoute from './v1/userPlan/userPlan.route';
import twoFactorAuthRoute from './twoFactorAuth.route';
import subscriptionRoute from './v1/subscription/subscription.route';
import mobileNumberRequestRoute from './v1/mobileNumberRequest/mobileNumberRequest.route';
import cancelRequestRoute from './v1/cancelPlan/cancelPlan.route';
import claimRequestRoute from './v1/claimRequest/claimRequest.route';

const router = express.Router();
router.use('/user', userRoutes);
router.use('/test', testRoutes);
router.use('/auth', authRoutes);
router.use('/address', addressRoutes);
router.use('/userProfessionalDetail', userProfessionalDetailRoutes);
router.use('/friend', friendRoutes);
router.use('/story', storyRoute);
router.use('/blog', blogRoute);
router.use('/shortlist', ShortlistRoute);
router.use('/profile-viewer', profileviwerRoute);
router.use('/message', MessageRoute);
router.use('/privacy', privacyRoute);
router.use('/email-notification', EmailNotificationRoute);
router.use('/notification', NotificationRoute);
router.use('/plan', PlanRoute);
router.use('/search', serachRoute);
router.use('/like', likeRoute);
router.use('/userEducation', EducationRoute);
router.use('/partner', PratnerRoute);
router.use('/status', StatusRoute);
router.use('/emoji', EmojiRoute);
router.use('/offer', OfferRoute);
router.use('/message-consent', MessageConsentRoute);
router.use('/razorpay', razorpayRoute);
router.use('/search-history', searchHistoryRoute);
router.use('/spam', spamUserRoute);
router.use('/story-view', storyViewRoute);
router.use('/kyc', KycRoute);
router.use('/dating-partner', datingPartnerRoute);
router.use('/country-code', countryCodeRoute);
router.use('/success-story-View', SuccessStoryViewRoute);
router.use('/story-Like', StoryLikeRoute);
router.use('/user-plan', userPlanRoute);
router.use('/2fa', twoFactorAuthRoute);
router.use('/subscription', subscriptionRoute);
router.use('/mobile-number-request', mobileNumberRequestRoute);
router.use('/cancel-plan-request', cancelRequestRoute);
router.use('/claim-request', claimRequestRoute);

// router.use('/userEducation', userEducationRoutes);
// router.use('/commentOnStory', commentOnStoryRoutes);
// router.use('/commentsOnBlog', commentsOnBlogRoutes);
// router.use('/notification', notificationRoutes);

module.exports = router;
