const EnumCodeTypeOfCode = {
  RESETPASSWORD: 'resetPassword',
  LOGIN: 'login',
  RESET_LOGIN_CRED: 'resetLoginCred',
};
const EnumRoleOfUser = {
  USER: 'user',
  ADMIN: 'admin',
  PROJECT_OWNER: 'project-owner',
  SUPER_ADMIN: 'super-admin',
  CO_ADMIN: 'co-admin',
};
const EnumPlatformOfDeviceToken = {
  ANDROID: 'android',
  IOS: 'ios',
  WEB: 'web',
};
const EnumTypeOfToken = {
  RESET_PASSWORD: 'resetPassword',
  VERIFY_EMAIL: 'verifyEmail',
  REFRESH: 'refresh',
  STORY_CONSENT: 'story_consent',
};
const EnumAppUsesTypeOfUsers = {
  MARRIAGE: 'marriage',
  DATING: 'dating',
  SOCIAL: 'social',
  VENDOR: 'vendor',
  ALL: 'all',
};
const EnumGenderOfUsers = {
  MALE: 'male',
  FEMALE: 'female',
  NON_BINARY: 'nonBinary',
  PREFER_NOT_TO_SAY: 'preferNotToSay',
  OTHER: 'other',
};

const EnumStatusOfFriend = {
  REQUESTED: 'requested',
  RECEIVED: 'received',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  REMOVED: 'removed',
  BLOCKED: 'blocked',
};

const EnumCreatingProfileFor = {
  MY_SELF: 'mySelf',
  MY_SON: 'mySon',
  MY_DAUGHTER: 'myDaughter',
  MY_BROTHER: 'myBrother',
  MY_FRIEND: 'myFriend',
  MY_RELATIVES: 'myRelatives',
  MY_COUSIN: 'myCousin',
  MY_NEPHEW: 'myNephew',
};

const EnumOfPlan = {
  GOLD: 'gold',
  PLATINUM: 'Platinum',
  SILVER: 'silver',
  DATING: 'dating',
};
const EnumOfOnlineSupport = {
  YES: 'yes',
  No: 'no',
};
const EnumOfPlanDuration = {
  MONTHLY: 'monthly',
  TWO_MONTHLY: 'two-month',
  THREE_MONTHLY: 'three-month',
  YEARLY: 'yearly',
  QUARTERLY: 'quarterly',
  BIANNUAL: 'biannual',
};
const EnumOfStatus = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
};
const EnumOfMaritalStatus = {
  SINGLE: 'single',
  NEVER_MARRIED: 'neverMarried',
  MARRIED: 'married',
  DIVORCEE: 'divorcee',
};

const EnumOfReligion = {
  HINDU: 'hindu',
  MUSLIM: 'muslim',
  CHRISTIAN: 'christian',
  SIKH: 'sikh',
  BUDDHIST: 'buddhist',
  JAIN: 'jain',
  ISLAM: 'islam',
  OTHER: 'other',
};

const EnumOfCommunity = {
  PATEL: 'patel',
  SHAH: 'shah',
  SONI: 'soni',
};
const EnumOfMotherTongue = {
  ASSAMESE: 'assamese',
  BENGALI: 'bengali',
  BODO: 'bodo',
  DOGRI: 'dogri',
  GUJARATI: 'gujarati',
  HINDI: 'hindi',
  KANNADA: 'kannada',
  KASHMIRI: 'kashmiri',
  KONKINI: 'konkini',
  MANIPURI: 'manipuri',
  MARATHI: 'marathi',
  NEPALI: 'nepali',
  ODIA: 'odia',
  PUNJABI: 'punjabi',
  SANSKRIT: 'sanskrit',
  SANTALI: 'santali',
  SINDHI: 'sindhi',
  TAMIL: 'tamil',
  TELUGU: 'telugu',
  URDU: 'urdu',
  ENGLISH: 'english',
};

const EnumOflanguage = {
  GUJARATI: 'gujarati',
  HINDI: 'hindi',
  ENGLISH: 'english',
};
const EnumOfManglikStatus = {
  MANGLIK: 'manglik',
  NON_MANGLIK: 'non-manglik',
  ANSHIK_MANGLIK: 'anshik-manglik',
  DONT_KNOW: 'dont-know',
};

const EnumOfCurrentCountry = {
  INDIA: 'india',
};
const EnumOfState = {
  ANDHRA_PRADESH: 'andhra-pradesh',
  ARUNACHAL_PRADESH: 'arunachal-pradesh',
  ASSAM: 'assam',
  BIHAR: 'bihar',
  CHHATTISGARH: 'chhattisgarh',
  GOA: 'goa',
  GUJARAT: 'gujarat',
  HARYANA: 'haryana',
  HIMACHAL_PRADESH: 'himachal-pradesh',
  JHARKHAND: 'jharkhand',
  KARNATAKA: 'karnataka',
  KERALA: 'kerala',
  MADHYA_PRADESH: 'madhya-pradesh',
  MAHARASHTRA: 'maharashtra',
  MANIPUR: 'manipur',
  MEGHALAYA: 'meghalaya',
  MIZORAM: 'mizoram',
  NAGALAND: 'nagaland',
  ODISHA: 'odisha',
  PUNJAB: 'punjab',
  RAJASTHAN: 'rajasthan',
  SIKKIM: 'sikkim',
  TAMIL_NADU: 'tamil-nadu',
  TELANGANA: 'telangana',
  TRIPURA: 'tripura',
  UTTAR_PRADESH: 'uttar-pradesh',
  UTTARAKHAND: 'uttarakhand',
  WEST_BENGAL: 'west-bengal',
};

const EnumOfCountry = {
  INDIA: 'india',
  AUSTRALIA: 'australia',
  CANADA: 'canada',
  US: 'us',
  UAE: 'uae',
  JAPAN: 'japan',
  SINGAPORE: 'singapore',
  FRANCE: 'france',
  UNITED_KINGDOM: 'united-kingdom',
  CHINA: 'china',
  MYANMAR: 'myanmar',
  NEPAL: 'nepal',
  SRI_LANKA: 'sri-lanka',
};

const EnumOfCreative = {
  WRITING: 'writing',
  PAINTING: 'painting',
};
const EnumOfDiet = {
  VEGETARIAN: 'vegetarian',
  EGGETARIAN: 'eggetarian',
  NON_VEGETARIAN: 'non_vegetarian',
  VEGAN: 'vegan',
  JAIN: 'jain',
  OCCASIONALLY_NON_VEGETARIAN: 'occasionally_non_vegetarian',
  OCCASIONALLY_VEGETARIAN: 'occasionally_vegetarian',
  SATVIK: 'satvik',
  OTHER: 'other',
};

const EnumOfPrivacySetting = {
  PRIVATE_PROFILE: 'privateProfile',
  PREMIUM_PROFILE: 'premiumProfile',
  ONLY_ACCEPTED_MEMBERS: 'onlyAcceptedMembers',
  DEFAULT: 'default',
  PUBLIC_PROFILE: 'publicProfile',
};

const EnumForTimeDurationOfProfileHide = {
  ONE_WEEK: 'oneWeek',
  TWO_WEEK: 'twoWeek',
  ONE_MONTH: 'oneMonth',
  THREE_MONTH: 'threeMonth',
  SIX_MONTH: 'sixMonth',
};
const EnumOfReasonForProfileDelete = {
  FOUND_SUITABLE_PARTNER: 'found-suitable-partner',
  MARRIED_OR_ENGAGED: 'married-or-engaged',
  TAKING_BREAK: 'taking-break',
  PRIVACY_OR_SAFETY_CONCERNS: 'privacy-or-safety-concerns',
  DIFFICULT_TO_USE: 'difficult-to-use',
  TOO_MANY_UNRELATED_MATCHES: 'too-many-unrelated-matches',
  DID_NOT_GET_EXPECTED_RESPONSES: 'did-not-get-expected-responses',
  TOO_COSTLY_OR_NOT_VALUABLE: 'too-costly-or-not-valuable',
  OTHER: 'other',
};

const EnumOfImageTypes = {
  PROFILE_IMAGE: 'profileImage',
  STATUS_IMAGE: 'statusImage',
  PROFILE_VIDEO: 'profileVideo',
};

const EnumOfHobby = {
  WRITING: 'writing',
  PLAY_INSTRUMENT: 'play_instrument',
  POETRY: 'poetry',
  COOKING: 'cooking',
  PAINTING: 'painting',
  GARDENING: 'gardening',
  SINGING: 'singing',
  DIY_CRAFTS: 'diy_crafts',
  BLOGGING: 'blogging',
  PHOTOGRAPHY: 'photography',
  DANCING: 'dancing',
  CONTENT_CREATION: 'content_creation',
  MOVIE: 'movie',
  SPORTS: 'sports',
  BIKING: 'biking',
  MUSIC: 'music',
  SOCIAL_MEDIA: 'social_media',
  CLUBBING: 'clubbing',
  TRAVELLING: 'travelling',
  GAMING: 'gaming',
  SHOPPING: 'shopping',
  READING: 'reading',
  BINGE_WATCHING: 'binge_watching',
  THEATER_EVENTS: 'theater_events',
  RUNNING: 'running',
  CYCLING: 'cycling',
  YOGA: 'yoga',
  WALKING: 'walking',
  WORKING_OUT: 'working_out',
  TREKKING: 'trekking',
  AEROBICS_ZUMBA: 'aerobics_zumba',
  SWIMMING: 'swimming',
};

const EnumOfNotification = {
  REQUEST_SENT: 'Request-sent',
  REQUEST_DECLINED: 'Declined your request',
  REQUEST_RECEIVED: 'Sent you a request',
  REQUEST_ACCEPTED: 'accepted your request',
  LIKE: 'like',
  SOMEONE_LIKED_YOUR_PROFILE: 'likes you',
  OTP_SEND: 'otp has been sent to your registered email',
  RESET_PASS: 'link has been sent to your registered email',
  CONGRATULATION:
    'Welcome to HappyMilan! We are thrilled to have you as a part of our community. Congratulations on successfully registering your account.',
};
const EnumOfChatType = {
  IMAGE: 'image',
  DOC: 'doc',
  LINK: 'link',
  REPLY: 'reply',
  TEXT: 'text',
  VIDEO: 'video',
  AUDIO: 'audio',
};
const EnumOfOffer = {
  FESTIVAL: 'festival',
  OFFER: 'offer',
  PROMOTION: 'promotion',
};

const EnumOfUserPlan = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  EXPIRED: 'expired',
};
const EnumOfGothra = {
  BHARADVAJA: 'Bharadvaja',
  KASHYAPA: 'Kashyapa',
  ATRI: 'Atri',
  VASHISTHA: 'Vashistha',
  VISHWAMITRA: 'Vishwamitra',
  GAUTAMA: 'Gautama',
  JAMADAGNI: 'Jamadagni',
  AGASTYA: 'Agastya',
  BHRIGU: 'Bhrigu',
  KAUSHIKA: 'Kaushika',
  SANDILYA: 'Sandilya',
  PARASHARA: 'Parashara',
  MANDAVYA: 'Mandavya',
  HARITA: 'Harita',
  KUTSA: 'Kutsa',
  SHRIVATSA: 'Shrivatsa',
  MUDGALA: 'Mudgala',
  VATSA: 'Vatsa',
  MAITREYA: 'Maitreya',
  DURVASA: 'Durvasa',
  CHYAVANA: 'Chyavana',
  MARICHI: 'Marichi',
  PULASTYA: 'Pulastya',
  PULAHA: 'Pulaha',
  KRATU: 'Kratu',
  ANGIRASA: 'Angirasa',
  VISHNUVARDHANA: 'Vishnuvardhana',
  SHUNAKA: 'Shunak',
  KAPILA: 'Kapila',
  VYASA: 'Vyasa',
  RISHYASHRINGA: 'Rishyashringa',
  SANKRITI: 'Sankriti',
  SAUNAKA: 'Saunaka',
  ROHINI: 'Rohini',
  LOMASHA: 'Lomasha',
  DEVALA: 'Devala',
  YAJNAVALKYA: 'Yajnavalkya',
  VALMIKI: 'Valmiki',
  GALAVA: 'Galava',
  VAMADEVA: 'Vamadeva',
  OTHER: 'Other',
};

const EnumOfReason = {
  JUST_DONT_LIKE_IT: 'just-dont-like-it',
  ITS_SPAM: 'its-spam',
  NUDITY_OR_SEXUAL_ACTIVITY: 'nudity-or-sexual-activity',
  BULLYING_OR_HARASSMENT: 'bullying-or-harassment',
  SCAM_OR_FRAUD: 'scam-or-fraud',
};

// todo : add this enum in data base and handle from main admin panel
const EnumOfPlatformType = {
  HAPPY_MILAN: 'happyMilan',
  BUSINESS_PLATFORM: 'businessPlatform',
};
const EnumOfKyc = {
  PASSPORT: 'passport',
  DRIVING_LICENSE: 'driving-license',
  AADHAR_CARD: 'aadhar-card',
  ELECTION_CARD: 'election-card',
  SELFIE: 'selfie',
};
const EnumOfInterest = {
  MEET_NEW_FRIENDS: 'meet-new-friends',
  LOOKING_FOR_LOVE: 'looking-for-love',
  MOVIE_DATE: 'movie-date',
  FOODIES: 'foodies',
  TRAVEL_BUDDIES: 'travel-buddies',
  GAME_LOVER: 'game-lover',
  CHITCHAT: 'chit-chat',
  ADVENTUROUS: 'adventurous',
};
const EnumOf2faMethod = {
  AUTHENTICATOR_APP: 'authenticator-app',
  OTP: 'otp',
};
const EnumOfZodiac = {
  ARIES: 'Aries',
  TAURUS: 'Taurus',
  GEMINI: 'Gemini',
  CANCER: 'Cancer',
  LEO: 'Leo',
  VIRGO: 'Virgo',
  LIBRA: 'Libra',
  SCORPIO: 'Scorpio',
  SAGITTARIUS: 'Sagittarius',
  CAPRICORN: 'Capricorn',
  AQUARIUS: 'Aquarius',
  PISCES: 'Pisces',
};

const EnumOfBlogType = {
  BLOGS: 'blogs',
  VIDEO: 'video',
  PHOTOS: 'photos',
};
const EnumOfCancelReason = {
  ACCIDENTAL_PURCHASE: 'accidental-purchase', // Accidental purchase / wrong plan selected
  CHANGED_MIND: 'changed-mind', // Changed mind before using premium features
  TECHNICAL_ISSUES: 'technical-issues', // Technical issues after upgrade
  OTHER: 'other', // Other reason
};
const EnumOfRefundStatus = {
  PENDING: 'pending',
  PROCESSED: 'processed',
  NOT_APPLICABLE: 'not_applicable',
};
const EnumOfJobType = {
  GOVERNMENT: 'government',
  PRIVATE: 'private',
  RETIRED: 'retired',
  // STUDENT: 'student',
  // PREFER_NOT_TO_SAY: 'prefer_not_to_say',
  // NOT_WORKING: 'not_working',
  HOMEMAKER: 'homemaker',
};
const EnumOfDegree = {
  BACHELORS_ARTS: 'Bachelors Arts',
  BACHELORS_SCIENCE: 'Science',
  BACHELORS_COMMERCE: 'Commerce',
  B_PHIL: 'B Phil',
  BACHELORS_ENGINEERING: 'Bachelors Engineering',
  COMPUTERS: 'Computers',
  BCA: 'BCA',
  MCA: 'MCA',
  BBA: 'BBA',
  BSC: 'BSC',
  MSC: 'MSC',
  DIPLOMA: 'Diploma',
  HIGHER_SECONDARY: 'Higher Secondary',
  SECONDARY: 'Secondary',
  LEGAL_BL: 'Legal BL',
  ML: 'ML',
  LLB: 'LLB',
  LLM: 'LLM',
  MANAGEMENT_BBA: 'Management BBA',
  MBA: 'MBA',
  MASTERS_ARTS: 'Masters Arts',
  MASTERS_SCIENCE: 'Masters Science',
  MASTERS_COMMERCE: 'Masters Commerce',
  M_PHIL: 'M Phil',
  MASTERS_ENGINEERING: 'Masters Engineering',
  MASTERS_COMPUTERS: 'Computers (Masters)',
  MEDICINE_GENERAL: 'Medicine General',
  DENTAL: 'Dental',
  SURGEON: 'Surgeon',
  PHD: 'Ph.D',
  SERVICE_IAS: 'IAS',
  SERVICE_IPS: 'IPS',
  SERVICE_IRS: 'IRS',
  SERVICE_IES: 'IES',
  SERVICE_IFS: 'IF',
};
const EnumOfAdminRejectReason = {
  PREMIUM_FEATURES_UTILIZED: 'Premium features already utilized',
  OUTSIDE_REFUND_ELIGIBILITY: 'Request made outside refund eligibility period',
  ONGOING_COMMUNICATION: 'Ongoing communication with other members under current plan',
  CHARGEBACK_INITIATED: 'Chargeback/dispute already initiated with payment gateway',
  PLAN_EXPIRED: 'Request submitted after plan validity expired',
};
const EnumOfbusinessType = {
  PHOTO_STUDIO: 'photo-studio',
  CATERING: 'catering',
  WEDDING_PLANNER: 'wedding-planner',
  DECORATION: 'decoration',
  JEWELLERY_SHOPS: 'jewellery-shops',
  BEAUTY_SALON: 'beauty-salon',
  MEETING_POINTS: 'meeting-points',
  BEAUTY_MAKEUP: 'beauty-make-up',
  FITNESS_CENTERS: 'fitness-centers',
  YOGA_CENTERS: 'yoga-centers',
};

const EnumOfServicesProvided = {
  WEDDING_PHOTOGRAPHY: 'wedding-photography',
  PRE_WEDDING_PHOTOGRAPHY: 'pre-wedding-photography',
  ENGAGEMENT_PHOTOGRAPHY: 'engagement-photography',
  MATERNITY_PHOTOGRAPHY: 'maternity-photography',
  NEWBORN_OR_BABY_PHOTOGRAPHY: 'newborn-or-baby-photography',
  KIDS_PHOTOGRAPHY: 'kids-photography',
  FAMILY_PORTRAIT_PHOTOGRAPHY: 'family-portrait-photography',
  COUPLE_PHOTOGRAPHY: 'couple-photography',
  FASHION_PHOTOGRAPHY: 'fashion-photography',
  MODEL_PORTFOLIO_PHOTOGRAPHY: 'model-portfolio-photography',
  CORPORATE_BUSINESS_PHOTOGRAPHY: 'corporate-business-photography',
  PRODUCT_PHOTOGRAPHY: 'product-photography',
  FOOD_PHOTOGRAPHY: 'food-photography',
  REAL_ESTATE_PROPERTY_PHOTOGRAPHY: 'real-estate-property-photography',
  EVENT_PHOTOGRAPHY_BIRTHDAY_PARTY_CORPORATE_EVENT: 'event-photography-birthday-party-corporate-event',
  PASSPORT_SIZE_PHOTO: 'passport-size-photo',
  ID_VISA_PHOTO: 'id-visa-photo',
  WEDDING_VIDEOGRAPHY: 'wedding-videography',
  PRE_WEDDING_CINEMATIC_VIDEO: 'pre-wedding-cinematic-video',
  EVENT_VIDEOGRAPHY: 'event-videography',
  CORPORATE_VIDEO_SHOOT: 'corporate-video-shoot',
  MUSIC_VIDEO_SHOOT: 'music-video-shoot',
  YOUTUBE_SOCIAL_MEDIA_VIDEO_SHOOT: 'youtube-social-media-video-shoot',
  DRONE_VIDEOGRAPHY: 'drone-videography',
  PHOTO_EDITING_RETOUCHING: 'photo-editing-retouching',
  BACKGROUND_REMOVAL_CHANGE: 'background-removal-change',
  PHOTO_RESTORATION_OLD_PHOTOS_REPAIR: 'photo-restoration-old-photos-repair',
  ALBUM_DESIGN: 'album-design',
  WEDDING_ALBUM_DESIGN: 'wedding-album-design',
  PHOTO_COLOR_CORRECTION: 'photo-color-correction',
  PHOTO_PRINTING: 'photo-printing',
  CANVAS_PRINTING: 'canvas-printing',
  PHOTO_FRAMES: 'photo-frames',
  PHOTO_ALBUMS: 'photo-albums',
  MUG_TSHIRT_PHOTO_PRINTING: 'mug-tshirt-photo-printing',
  PHOTO_LAMINATION: 'photo-lamination',
  STUDIO_RENTAL_FOR_PHOTOSHOOT: 'studio-rental-for-photoshoot',
  MAKEUP_ARTIST_FOR_PHOTOSHOOT: 'makeup-artist-for-photoshoot',
  PROPS_COSTUME_RENTAL: 'props-costume-rental',
  GREEN_SCREEN_PHOTOGRAPHY: 'green-screen-photography',

  WEDDING_CONSULTATION: 'wedding-consultation',
  BUDGET_PLANNING: 'budget-planning',
  VENUE_SELECTION: 'venue-selection',
  THEME_CONCEPT_DESIGN: 'theme-concept-design',
  VENDOR_SELECTION_MANAGEMENT: 'vendor-selection-management',
  WEDDING_TIMELINE_PLANNING: 'wedding-timeline-planning',
  GUEST_LIST_MANAGEMENT: 'guest-list-management',
  INVITATION_RSVP_MANAGEMENT: 'invitation-rsvp-management',
  CATERING_ARRANGEMENT: 'catering-arrangement',
  PHOTOGRAPHY_VIDEOGRAPHY: 'photography-videography',
  DECORATION_FLORAL_DESIGN: 'decoration-floral-design',
  ENTERTAINMENT_DJ_BAND_PERFORMERS: 'entertainment-dj-band-performers',
  MAKEUP_STYLING_ARTISTS: 'makeup-styling-artists',
  WEDDING_CAKE_ARRANGEMENT: 'wedding-cake-arrangement',
  LIGHTING_SOUND_SETUP: 'lighting-sound-setup',
  TRANSPORTATION_GUEST_LOGISTICS: 'transportation-guest-logistics',
  CEREMONY_PLANNING: 'ceremony-planning',
  RECEPTION_PLANNING: 'reception-planning',
  STAGE_MANDAP_SETUP: 'stage-mandap-setup',
  WEDDING_DAY_COORDINATION: 'wedding-day-coordination',
  GUEST_HOSPITALITY_MANAGEMENT: 'guest-hospitality-management',
  SECURITY_CROWD_MANAGEMENT: 'security-crowd-management',
  DESTINATION_WEDDING_PLANNING: 'destination-wedding-planning',
  CULTURAL_TRADITIONAL_CEREMONY_PLANNING: 'cultural-traditional-ceremony-planning',
  PRE_WEDDING_EVENTS: 'pre-wedding-events',
  HONEYMOON_PLANNING: 'honeymoon-planning',
  BRIDAL_GROOM_STYLING: 'bridal-groom-styling',
  WEDDING_WEBSITE_DIGITAL_INVITATION: 'wedding-website-digital-invitation',
  GIFT_MANAGEMENT: 'gift-management',
  THANK_YOU_CARD_ARRANGEMENTS: 'thank-you-card-arrangements',
  ALBUM_VIDEO_DELIVERY: 'album-video-delivery',
  VENDOR_PAYMENT_COORDINATION: 'vendor-payment-coordination',

  WEDDING_DECORATION: 'wedding-decoration',
  ENGAGEMENT_DECORATION: 'engagement-decoration',
  RECEPTION_DECORATION: 'reception-decoration',
  BIRTHDAY_PARTY_DECORATION: 'birthday-party-decoration',
  ANNIVERSARY_DECORATION: 'anniversary-decoration',
  BABY_SHOWER_DECORATION: 'baby-shower-decoration',
  MEHNDI_HALDI_DECORATION: 'mehndi-haldi-decoration',
  SANGEET_DECORATION: 'sangeet-decoration',
  RING_CEREMONY_DECORATION: 'ring-ceremony-decoration',
  PROPOSAL_DECORATION: 'proposal-decoration',
  CORPORATE_EVENT_DECORATION: 'corporate-event-decoration',
  STAGE_DECORATION: 'stage-decoration',
  EXHIBITION_STALL_DECORATION: 'exhibition-stall-decoration',
  CONFERENCE_DECORATION: 'conference-decoration',
  PRODUCT_LAUNCH_DECORATION: 'product-launch-decoration',
  THEME_PARTY_DECORATION: 'theme-party-decoration',
  FLORAL_DECORATION: 'floral-decoration',
  BALLOON_DECORATION: 'balloon-decoration',
  LIGHT_DECORATION: 'light-decoration',
  MANDAP_DECORATION: 'mandap-decoration',
  ENTRANCE_GATE_DECORATION: 'entrance-gate-decoration',
  TABLE_CHAIR_DECORATION: 'table-chair-decoration',
  CEILING_DECORATION: 'ceiling-decoration',
  BACKDROP_DECORATION: 'backdrop-decoration',
  GARDEN_OUTDOOR_DECORATION: 'garden-outdoor-decoration',
  DESTINATION_WEDDING_DECORATION: 'destination-wedding-decoration',
  CAR_DECORATION: 'car-decoration',
  HOUSE_DECORATION_FOR_EVENTS: 'house-decoration-for-events',
  FESTIVAL_DECORATION: 'festival-decoration',
  CUSTOMIZED_THEME_DECORATION: 'customized-theme-decoration',

  GOLD_JEWELLERY: 'gold-jewellery',
  DIAMOND_JEWELLERY: 'diamond-jewellery',
  SILVER_JEWELLERY: 'silver-jewellery',
  PLATINUM_JEWELLERY: 'platinum-jewellery',
  BRIDAL_JEWELLERY: 'bridal-jewellery',
  ANTIQUE_JEWELLERY: 'antique-jewellery',
  TEMPLE_JEWELLERY: 'temple-jewellery',
  CUSTOM_JEWELLERY: 'custom-jewellery',
  KIDS_JEWELLERY: 'kids-jewellery',
  CUSTOM_JEWELLERY_DESIGN: 'custom-jewellery-design',
  PERSONALIZED_NAME_JEWELLERY: 'personalized-name-jewellery',
  BRIDAL_JEWELLERY_DESIGN: 'bridal-jewellery-design',
  JEWELLERY_REMODELING_REDESIGN: 'jewellery-remodeling-redesign',
  JEWELLERY_REPAIR: 'jewellery-repair',
  RING_RESIZING: 'ring-resizing',
  STONE_REPLACEMENT: 'stone-replacement',
  JEWELLERY_POLISHING: 'jewellery-polishing',
  JEWELLERY_CLEANING: 'jewellery-cleaning',
  DIAMOND_CERTIFICATION: 'diamond-certification',
  JEWELLERY_VALUATION_APPRAISAL: 'jewellery-valuation-appraisal',
  HALLMARK_GOLD_JEWELLERY: 'hallmark-gold-jewellery',
  GOLD_EXCHANGE: 'gold-exchange',
  OLD_GOLD_PURCHASE: 'old-gold-purchase',
  GOLD_COINS_BARS: 'gold-coins-bars',
  JEWELLERY_BUYBACK: 'jewellery-buyback',
  BRIDAL_JEWELLERY_RENTAL: 'bridal-jewellery-rental',
  JEWELLERY_ENGRAVING: 'jewellery-engraving',
  JEWELLERY_INSURANCE_ASSISTANCE: 'jewellery-insurance-assistance',
  JEWELLERY_GIFT_PACKAGING: 'jewellery-gift-packaging',

  BRIDAL_HD_MAKEUP: 'bridal-hd-makeup',
  AIRBRUSH_BRIDAL_MAKEUP: 'airbrush-bridal-makeup',
  TRADITIONAL_BRIDAL_MAKEUP: 'traditional-bridal-makeup',
  RECEPTION_MAKEUP: 'reception-makeup',
  ENGAGEMENT_MAKEUP: 'engagement-makeup',
  PARTY_MAKEUP_SANGEET_MEHENDI: 'party-makeup-sangeet-mehendi',

  BRIDAL_HAIR_STYLING: 'bridal-hair-styling',
  BRIDAL_BUN: 'bridal-bun',
  CURLS_BRAIDS_WAVES: 'curls-braids-waves',
  HAIR_EXTENSIONS: 'hair-extensions',
  HAIR_ACCESSORIES_SETTING: 'hair-accessories-setting',

  PRE_BRIDAL_SKIN_CARE_TREATMENT: 'pre-bridal-skin-care-treatment',
  FACIAL_SKIN_GLOW_TREATMENT: 'facial-skin-glow-treatment',
  BODY_POLISHING: 'body-polishing',
  DETAN_BLEACH: 'detan-bleach',
  FULL_BODY_WAXING: 'full-body-waxing',
  THREADING_EYEBROW_SHAPING: 'threading-eyebrow-shaping',
  HAIR_SPA: 'hair-spa',
  KERATIN_TREATMENT: 'keratin-treatment',
  DEEP_CONDITIONING_TREATMENT: 'deep-conditioning-treatment',
  HAIR_COLOR_HIGHLIGHTS: 'hair-color-highlights',
  BRIDAL_MANICURE: 'bridal-manicure',
  BRIDAL_PEDICURE: 'bridal-pedicure',
  NAIL_ART: 'nail-art',
  BODY_MASSAGE: 'body-massage',
  BODY_WRAP: 'body-wrap',
  AROMATHERAPY_TREATMENT: 'aromatherapy-treatment',
  RELAXATION_SPA: 'relaxation-spa',
  BRIDAL_MAKEUP_TRIAL: 'bridal-makeup-trial',
  BRIDAL_HAIR_TRIAL: 'bridal-hair-trial',
  SKIN_HAIR_CONSULTATION: 'skin-hair-consultation',
  GROOM_MAKEUP_PACKAGE: 'groom-makeup-package',
  BRIDESMAID_MAKEUP: 'bridesmaid-makeup',
  GUEST_MAKEUP_HAIRSTYLING: 'guest-makeup-hairstyling',

  CAFES_COFFEE_SHOPS: 'cafes-coffee-shops',
  RESTAURANTS: 'restaurants',
  PARKS_GARDENS: 'parks-gardens',
  MALLS_SHOPPING_CENTERS: 'malls-shopping-centers',
  LOUNGES_BARS: 'lounges-bars',
  BEACH_SPOTS: 'beach-spots',
  CULTURAL_CENTERS: 'cultural-centers',
  CO_WORKING_SPACES: 'co-working-spaces',
  EVENT_VENUES: 'event-venues',
  PRIVATE_MEETING_ROOMS: 'private-meeting-rooms',
  HOTEL_LOBBIES: 'hotel-lobbies',
  ROOFTOP_CAFES: 'rooftop-cafes',
  BOOK_CAFES: 'book-cafes',
  ART_GALLERIES: 'art-galleries',
  ENTERTAINMENT_ZONES: 'entertainment-zones',
  CINEMA_MOVIE_THEATRES: 'cinema-movie-theatres',
  COMMUNITY_CENTERS: 'community-centers',
  TOURIST_ATTRACTIONS: 'tourist-attractions',
  PICNIC_SPOTS: 'picnic-spots',
  SPIRITUAL_PREMISES: 'spiritual-premises',
  FIRST_DATE_SPOTS: 'first-date-spots',
  SAFE_PUBLIC_MEETING_SPOTS: 'safe-public-meeting-spots',
  GROUP_MEETUP_PLACES: 'group-meetup-places',
  ROMANTIC_DATE_LOCATIONS: 'romantic-date-locations',
  ACTIVITY_BASED_MEETING_POINTS: 'activity-based-meeting-points',

  BRIDAL_MAKEUP: 'bridal-makeup',
  PRE_WEDDING_MAKEUP: 'pre-wedding-makeup',
  DESTINATION_WEDDING_MAKEUP: 'destination-wedding-makeup',
  PARTY_MAKEUP: 'party-makeup',
  EVENING_MAKEUP: 'evening-makeup',
  BIRTHDAY_MAKEUP: 'birthday-makeup',
  FESTIVAL_MAKEUP: 'festival-makeup',
  SPECIAL_OCCASION_MAKEUP: 'special-occasion-makeup',
  FASHION_MAKEUP: 'fashion-makeup',
  PHOTOSHOOT_MAKEUP: 'photoshoot-makeup',
  PORTFOLIO_MAKEUP: 'portfolio-makeup',
  MODEL_MAKEUP: 'model-makeup',
  TV_FILM_MAKEUP: 'tv-film-makeup',
  HD_BRIDAL_MAKEUP: 'hd-bridal-makeup',
  AIRBRUSH_MAKEUP: 'airbrush-makeup',
  CELEBRITY_STYLE_MAKEUP: 'celebrity-style-makeup',
  HAIRSTYLING: 'hairstyling',
  HAIR_SETTING_FOR_EVENTS: 'hair-setting-for-events',
  SAREE_DRAPING: 'saree-draping',
  EYELASH_EXTENSIONS: 'eyelash-extensions',
  EYEBROW_SHAPING_THREADING: 'eyebrow-shaping-threading',
  PRE_BRIDAL_SKINCARE: 'pre-bridal-skincare',
  FACIAL_CLEANUP: 'facial-cleanup',
  SKIN_POLISHING: 'skin-polishing',
  BRIDAL_BEAUTY_PACKAGES: 'bridal-beauty-packages',

  PERSONAL_TRAINING: 'personal-training',
  GROUP_FITNESS_CLASSES: 'group-fitness-classes',
  YOGA_CLASSES: 'yoga-classes',
  ZUMBA_CLASSES: 'zumba-classes',
  AEROBICS_CLASSES: 'aerobics-classes',
  CROSSFIT_TRAINING: 'crossfit-training',
  STRENGTH_TRAINING: 'strength-training',
  WEIGHT_LOSS_PROGRAMS: 'weight-loss-programs',
  WEIGHT_GAIN_PROGRAMS: 'weight-gain-programs',
  BODYBUILDING_TRAINING: 'bodybuilding-training',
  CARDIO_TRAINING: 'cardio-training',
  FUNCTIONAL_TRAINING: 'functional-training',
  PILATES_CLASSES: 'pilates-classes',
  MEDITATION_SESSIONS: 'meditation-sessions',
  NUTRITION_DIET_CONSULTATION: 'nutrition-diet-consultation',
  FITNESS_ASSESSMENT: 'fitness-assessment',
  BODY_COMPOSITION_ANALYSIS: 'body-composition-analysis',
  PHYSIOTHERAPY: 'physiotherapy',
  SPORTS_CONDITIONING: 'sports-conditioning',
  SENIOR_FITNESS_PROGRAMS: 'senior-fitness-programs',
  KIDS_FITNESS_PROGRAMS: 'kids-fitness-programs',
  ONLINE_FITNESS_COACHING: 'online-fitness-coaching',
  CORPORATE_FITNESS_PROGRAMS: 'corporate-fitness-programs',

  HATHA_YOGA: 'hatha-yoga',
  ASHTANGA_YOGA: 'ashtanga-yoga',
  VINYASA_FLOW_YOGA: 'vinyasa-flow-yoga',
  POWER_YOGA: 'power-yoga',
  IYENGAR_YOGA: 'iyengar-yoga',
  KUNDALINI_YOGA: 'kundalini-yoga',
  YIN_YOGA: 'yin-yoga',
  RESTORATIVE_YOGA: 'restorative-yoga',
  THERAPEUTIC_YOGA: 'therapeutic-yoga',
  YOGA_FOR_BACK_PAIN: 'yoga-for-back-pain',
  YOGA_FOR_WEIGHT_LOSS: 'yoga-for-weight-loss',
  YOGA_FOR_DIABETES: 'yoga-for-diabetes',
  YOGA_FOR_STRESS_RELIEF: 'yoga-for-stress-relief',
  YOGA_FOR_ANXIETY_DEPRESSION: 'yoga-for-anxiety-depression',
  PRENATAL_YOGA: 'prenatal-yoga',
  POSTNATAL_YOGA: 'postnatal-yoga',
  YOGA_FOR_SENIORS: 'yoga-for-seniors',
  GUIDED_MEDITATION: 'guided-meditation',
  MINDFULNESS_MEDITATION: 'mindfulness-meditation',
  PRANAYAMA: 'pranayama',
  SOUND_HEALING_MEDITATION: 'sound-healing-meditation',
  YOGA_NIDRA: 'yoga-nidra',
  CORPORATE_YOGA_PROGRAMS: 'corporate-yoga-programs',
  KIDS_YOGA_CLASSES: 'kids-yoga-classes',
  COUPLE_YOGA_SESSIONS: 'couple-yoga-sessions',
  PERSONAL_YOGA_TRAINING: 'personal-yoga-training',
  ONLINE_YOGA_CLASSES: 'online-yoga-classes',
  YOGA_WORKSHOPS: 'yoga-workshops',
  YOGA_RETREATS: 'yoga-retreats',
  DETOX_PROGRAMS: 'detox-programs',
  AYURVEDA_CONSULTATION: 'ayurveda-consultation',
  DIET_NUTRITION_GUIDANCE: 'diet-nutrition-guidance',
  HOLISTIC_WELLNESS_PROGRAMS: 'holistic-wellness-programs',
  SPIRITUAL_COUNSELING: 'spiritual-counseling',
};
module.exports = {
  EnumCodeTypeOfCode,
  EnumOfDegree,
  EnumRoleOfUser,
  EnumPlatformOfDeviceToken,
  EnumTypeOfToken,
  EnumAppUsesTypeOfUsers,
  EnumGenderOfUsers,
  EnumStatusOfFriend,
  EnumCreatingProfileFor,
  EnumOfStatus,
  EnumOfMaritalStatus,
  EnumOfPlanDuration,
  EnumOfOnlineSupport,
  EnumOfPlan,
  EnumOfReligion,
  EnumOfCommunity,
  EnumOfMotherTongue,
  EnumOfCurrentCountry,
  EnumOfRefundStatus,
  EnumOfState,
  EnumOfCountry,
  EnumOfCreative,
  EnumOfDiet,
  EnumOfPrivacySetting,
  EnumForTimeDurationOfProfileHide,
  EnumOfReasonForProfileDelete,
  EnumOfImageTypes,
  EnumOfNotification,
  EnumOfCancelReason,
  EnumOfChatType,
  EnumOfOffer,
  EnumOfUserPlan,
  EnumOfReason,
  EnumOfPlatformType,
  EnumOfKyc,
  EnumOfInterest,
  EnumOf2faMethod,
  EnumOfManglikStatus,
  EnumOfGothra,
  EnumOfZodiac,
  EnumOflanguage,
  EnumOfBlogType,
  EnumOfJobType,
  EnumOfHobby,
  EnumOfAdminRejectReason,
  EnumOfbusinessType,
  EnumOfServicesProvided,
};
